package socialite.visitors;

import socialite.eval.Worker;
import socialite.tables.TableInst;
import socialite.util.Assert;

public interface IVisitor extends Runnable, IntVisitor, ObjectVisitor {
	public void incPriority();
	public boolean hasPriority();
	
	public void setWorker(Worker w);
	public Worker getWorker();	
	public int getWorkerId();	
	
	public void run();
    public int getEpochId();
	public int getRuleId();	
	public TableInst[] getDeltaTables();
	public TableInst[] getPrivateTable();
	
	boolean visit_0(int a1);
	boolean visit_0(long a1);
	boolean visit_0(float a1);
	boolean visit_0(double a1);
	boolean visit_0(Object a1);
	boolean visit_1(int a1);
	boolean visit_1(long a1);
	boolean visit_1(float a1);
	boolean visit_1(double a1);
	boolean visit_1(Object a1);
	boolean visit_0_1(int a1,int a2);
	boolean visit_0_1(int a1,long a2);
	boolean visit_0_1(int a1,float a2);
	boolean visit_0_1(int a1,double a2);
	boolean visit_0_1(int a1,Object a2);
	boolean visit_0_1(long a1,int a2);
	boolean visit_0_1(long a1,long a2);
	boolean visit_0_1(long a1,float a2);
	boolean visit_0_1(long a1,double a2);
	boolean visit_0_1(long a1,Object a2);
	boolean visit_0_1(float a1,int a2);
	boolean visit_0_1(float a1,long a2);
	boolean visit_0_1(float a1,float a2);
	boolean visit_0_1(float a1,double a2);
	boolean visit_0_1(float a1,Object a2);
	boolean visit_0_1(double a1,int a2);
	boolean visit_0_1(double a1,long a2);
	boolean visit_0_1(double a1,float a2);
	boolean visit_0_1(double a1,double a2);
	boolean visit_0_1(double a1,Object a2);
	boolean visit_0_1(Object a1,int a2);
	boolean visit_0_1(Object a1,long a2);
	boolean visit_0_1(Object a1,float a2);
	boolean visit_0_1(Object a1,double a2);
	boolean visit_0_1(Object a1,Object a2);
	boolean visit_0_1_2(int a1,int a2,int a3);
	boolean visit_0_1_2(int a1,int a2,long a3);
	boolean visit_0_1_2(int a1,int a2,float a3);
	boolean visit_0_1_2(int a1,int a2,double a3);
	boolean visit_0_1_2(int a1,int a2,Object a3);
	boolean visit_0_1_2(int a1,long a2,int a3);
	boolean visit_0_1_2(int a1,long a2,long a3);
	boolean visit_0_1_2(int a1,long a2,float a3);
	boolean visit_0_1_2(int a1,long a2,double a3);
	boolean visit_0_1_2(int a1,long a2,Object a3);
	boolean visit_0_1_2(int a1,float a2,int a3);
	boolean visit_0_1_2(int a1,float a2,long a3);
	boolean visit_0_1_2(int a1,float a2,float a3);
	boolean visit_0_1_2(int a1,float a2,double a3);
	boolean visit_0_1_2(int a1,float a2,Object a3);
	boolean visit_0_1_2(int a1,double a2,int a3);
	boolean visit_0_1_2(int a1,double a2,long a3);
	boolean visit_0_1_2(int a1,double a2,float a3);
	boolean visit_0_1_2(int a1,double a2,double a3);
	boolean visit_0_1_2(int a1,double a2,Object a3);
	boolean visit_0_1_2(int a1,Object a2,int a3);
	boolean visit_0_1_2(int a1,Object a2,long a3);
	boolean visit_0_1_2(int a1,Object a2,float a3);
	boolean visit_0_1_2(int a1,Object a2,double a3);
	boolean visit_0_1_2(int a1,Object a2,Object a3);
	boolean visit_0_1_2(long a1,int a2,int a3);
	boolean visit_0_1_2(long a1,int a2,long a3);
	boolean visit_0_1_2(long a1,int a2,float a3);
	boolean visit_0_1_2(long a1,int a2,double a3);
	boolean visit_0_1_2(long a1,int a2,Object a3);
	boolean visit_0_1_2(long a1,long a2,int a3);
	boolean visit_0_1_2(long a1,long a2,long a3);
	boolean visit_0_1_2(long a1,long a2,float a3);
	boolean visit_0_1_2(long a1,long a2,double a3);
	boolean visit_0_1_2(long a1,long a2,Object a3);
	boolean visit_0_1_2(long a1,float a2,int a3);
	boolean visit_0_1_2(long a1,float a2,long a3);
	boolean visit_0_1_2(long a1,float a2,float a3);
	boolean visit_0_1_2(long a1,float a2,double a3);
	boolean visit_0_1_2(long a1,float a2,Object a3);
	boolean visit_0_1_2(long a1,double a2,int a3);
	boolean visit_0_1_2(long a1,double a2,long a3);
	boolean visit_0_1_2(long a1,double a2,float a3);
	boolean visit_0_1_2(long a1,double a2,double a3);
	boolean visit_0_1_2(long a1,double a2,Object a3);
	boolean visit_0_1_2(long a1,Object a2,int a3);
	boolean visit_0_1_2(long a1,Object a2,long a3);
	boolean visit_0_1_2(long a1,Object a2,float a3);
	boolean visit_0_1_2(long a1,Object a2,double a3);
	boolean visit_0_1_2(long a1,Object a2,Object a3);
	boolean visit_0_1_2(float a1,int a2,int a3);
	boolean visit_0_1_2(float a1,int a2,long a3);
	boolean visit_0_1_2(float a1,int a2,float a3);
	boolean visit_0_1_2(float a1,int a2,double a3);
	boolean visit_0_1_2(float a1,int a2,Object a3);
	boolean visit_0_1_2(float a1,long a2,int a3);
	boolean visit_0_1_2(float a1,long a2,long a3);
	boolean visit_0_1_2(float a1,long a2,float a3);
	boolean visit_0_1_2(float a1,long a2,double a3);
	boolean visit_0_1_2(float a1,long a2,Object a3);
	boolean visit_0_1_2(float a1,float a2,int a3);
	boolean visit_0_1_2(float a1,float a2,long a3);
	boolean visit_0_1_2(float a1,float a2,float a3);
	boolean visit_0_1_2(float a1,float a2,double a3);
	boolean visit_0_1_2(float a1,float a2,Object a3);
	boolean visit_0_1_2(float a1,double a2,int a3);
	boolean visit_0_1_2(float a1,double a2,long a3);
	boolean visit_0_1_2(float a1,double a2,float a3);
	boolean visit_0_1_2(float a1,double a2,double a3);
	boolean visit_0_1_2(float a1,double a2,Object a3);
	boolean visit_0_1_2(float a1,Object a2,int a3);
	boolean visit_0_1_2(float a1,Object a2,long a3);
	boolean visit_0_1_2(float a1,Object a2,float a3);
	boolean visit_0_1_2(float a1,Object a2,double a3);
	boolean visit_0_1_2(float a1,Object a2,Object a3);
	boolean visit_0_1_2(double a1,int a2,int a3);
	boolean visit_0_1_2(double a1,int a2,long a3);
	boolean visit_0_1_2(double a1,int a2,float a3);
	boolean visit_0_1_2(double a1,int a2,double a3);
	boolean visit_0_1_2(double a1,int a2,Object a3);
	boolean visit_0_1_2(double a1,long a2,int a3);
	boolean visit_0_1_2(double a1,long a2,long a3);
	boolean visit_0_1_2(double a1,long a2,float a3);
	boolean visit_0_1_2(double a1,long a2,double a3);
	boolean visit_0_1_2(double a1,long a2,Object a3);
	boolean visit_0_1_2(double a1,float a2,int a3);
	boolean visit_0_1_2(double a1,float a2,long a3);
	boolean visit_0_1_2(double a1,float a2,float a3);
	boolean visit_0_1_2(double a1,float a2,double a3);
	boolean visit_0_1_2(double a1,float a2,Object a3);
	boolean visit_0_1_2(double a1,double a2,int a3);
	boolean visit_0_1_2(double a1,double a2,long a3);
	boolean visit_0_1_2(double a1,double a2,float a3);
	boolean visit_0_1_2(double a1,double a2,double a3);
	boolean visit_0_1_2(double a1,double a2,Object a3);
	boolean visit_0_1_2(double a1,Object a2,int a3);
	boolean visit_0_1_2(double a1,Object a2,long a3);
	boolean visit_0_1_2(double a1,Object a2,float a3);
	boolean visit_0_1_2(double a1,Object a2,double a3);
	boolean visit_0_1_2(double a1,Object a2,Object a3);
	boolean visit_0_1_2(Object a1,int a2,int a3);
	boolean visit_0_1_2(Object a1,int a2,long a3);
	boolean visit_0_1_2(Object a1,int a2,float a3);
	boolean visit_0_1_2(Object a1,int a2,double a3);
	boolean visit_0_1_2(Object a1,int a2,Object a3);
	boolean visit_0_1_2(Object a1,long a2,int a3);
	boolean visit_0_1_2(Object a1,long a2,long a3);
	boolean visit_0_1_2(Object a1,long a2,float a3);
	boolean visit_0_1_2(Object a1,long a2,double a3);
	boolean visit_0_1_2(Object a1,long a2,Object a3);
	boolean visit_0_1_2(Object a1,float a2,int a3);
	boolean visit_0_1_2(Object a1,float a2,long a3);
	boolean visit_0_1_2(Object a1,float a2,float a3);
	boolean visit_0_1_2(Object a1,float a2,double a3);
	boolean visit_0_1_2(Object a1,float a2,Object a3);
	boolean visit_0_1_2(Object a1,double a2,int a3);
	boolean visit_0_1_2(Object a1,double a2,long a3);
	boolean visit_0_1_2(Object a1,double a2,float a3);
	boolean visit_0_1_2(Object a1,double a2,double a3);
	boolean visit_0_1_2(Object a1,double a2,Object a3);
	boolean visit_0_1_2(Object a1,Object a2,int a3);
	boolean visit_0_1_2(Object a1,Object a2,long a3);
	boolean visit_0_1_2(Object a1,Object a2,float a3);
	boolean visit_0_1_2(Object a1,Object a2,double a3);
	boolean visit_0_1_2(Object a1,Object a2,Object a3);
	boolean visit(int a1);
	boolean visit(long a1);
	boolean visit(float a1);
	boolean visit(double a1);
	boolean visit(Object a1);
	boolean visit(int a1,int a2);
	boolean visit(int a1,long a2);
	boolean visit(int a1,float a2);
	boolean visit(int a1,double a2);
	boolean visit(int a1,Object a2);
	boolean visit(long a1,int a2);
	boolean visit(long a1,long a2);
	boolean visit(long a1,float a2);
	boolean visit(long a1,double a2);
	boolean visit(long a1,Object a2);
	boolean visit(float a1,int a2);
	boolean visit(float a1,long a2);
	boolean visit(float a1,float a2);
	boolean visit(float a1,double a2);
	boolean visit(float a1,Object a2);
	boolean visit(double a1,int a2);
	boolean visit(double a1,long a2);
	boolean visit(double a1,float a2);
	boolean visit(double a1,double a2);
	boolean visit(double a1,Object a2);
	boolean visit(Object a1,int a2);
	boolean visit(Object a1,long a2);
	boolean visit(Object a1,float a2);
	boolean visit(Object a1,double a2);
	boolean visit(Object a1,Object a2);
	boolean visit(int a1,int a2,int a3);
	boolean visit(int a1,int a2,long a3);
	boolean visit(int a1,int a2,float a3);
	boolean visit(int a1,int a2,double a3);
	boolean visit(int a1,int a2,Object a3);
	boolean visit(int a1,long a2,int a3);
	boolean visit(int a1,long a2,long a3);
	boolean visit(int a1,long a2,float a3);
	boolean visit(int a1,long a2,double a3);
	boolean visit(int a1,long a2,Object a3);
	boolean visit(int a1,float a2,int a3);
	boolean visit(int a1,float a2,long a3);
	boolean visit(int a1,float a2,float a3);
	boolean visit(int a1,float a2,double a3);
	boolean visit(int a1,float a2,Object a3);
	boolean visit(int a1,double a2,int a3);
	boolean visit(int a1,double a2,long a3);
	boolean visit(int a1,double a2,float a3);
	boolean visit(int a1,double a2,double a3);
	boolean visit(int a1,double a2,Object a3);
	boolean visit(int a1,Object a2,int a3);
	boolean visit(int a1,Object a2,long a3);
	boolean visit(int a1,Object a2,float a3);
	boolean visit(int a1,Object a2,double a3);
	boolean visit(int a1,Object a2,Object a3);
	boolean visit(long a1,int a2,int a3);
	boolean visit(long a1,int a2,long a3);
	boolean visit(long a1,int a2,float a3);
	boolean visit(long a1,int a2,double a3);
	boolean visit(long a1,int a2,Object a3);
	boolean visit(long a1,long a2,int a3);
	boolean visit(long a1,long a2,long a3);
	boolean visit(long a1,long a2,float a3);
	boolean visit(long a1,long a2,double a3);
	boolean visit(long a1,long a2,Object a3);
	boolean visit(long a1,float a2,int a3);
	boolean visit(long a1,float a2,long a3);
	boolean visit(long a1,float a2,float a3);
	boolean visit(long a1,float a2,double a3);
	boolean visit(long a1,float a2,Object a3);
	boolean visit(long a1,double a2,int a3);
	boolean visit(long a1,double a2,long a3);
	boolean visit(long a1,double a2,float a3);
	boolean visit(long a1,double a2,double a3);
	boolean visit(long a1,double a2,Object a3);
	boolean visit(long a1,Object a2,int a3);
	boolean visit(long a1,Object a2,long a3);
	boolean visit(long a1,Object a2,float a3);
	boolean visit(long a1,Object a2,double a3);
	boolean visit(long a1,Object a2,Object a3);
	boolean visit(float a1,int a2,int a3);
	boolean visit(float a1,int a2,long a3);
	boolean visit(float a1,int a2,float a3);
	boolean visit(float a1,int a2,double a3);
	boolean visit(float a1,int a2,Object a3);
	boolean visit(float a1,long a2,int a3);
	boolean visit(float a1,long a2,long a3);
	boolean visit(float a1,long a2,float a3);
	boolean visit(float a1,long a2,double a3);
	boolean visit(float a1,long a2,Object a3);
	boolean visit(float a1,float a2,int a3);
	boolean visit(float a1,float a2,long a3);
	boolean visit(float a1,float a2,float a3);
	boolean visit(float a1,float a2,double a3);
	boolean visit(float a1,float a2,Object a3);
	boolean visit(float a1,double a2,int a3);
	boolean visit(float a1,double a2,long a3);
	boolean visit(float a1,double a2,float a3);
	boolean visit(float a1,double a2,double a3);
	boolean visit(float a1,double a2,Object a3);
	boolean visit(float a1,Object a2,int a3);
	boolean visit(float a1,Object a2,long a3);
	boolean visit(float a1,Object a2,float a3);
	boolean visit(float a1,Object a2,double a3);
	boolean visit(float a1,Object a2,Object a3);
	boolean visit(double a1,int a2,int a3);
	boolean visit(double a1,int a2,long a3);
	boolean visit(double a1,int a2,float a3);
	boolean visit(double a1,int a2,double a3);
	boolean visit(double a1,int a2,Object a3);
	boolean visit(double a1,long a2,int a3);
	boolean visit(double a1,long a2,long a3);
	boolean visit(double a1,long a2,float a3);
	boolean visit(double a1,long a2,double a3);
	boolean visit(double a1,long a2,Object a3);
	boolean visit(double a1,float a2,int a3);
	boolean visit(double a1,float a2,long a3);
	boolean visit(double a1,float a2,float a3);
	boolean visit(double a1,float a2,double a3);
	boolean visit(double a1,float a2,Object a3);
	boolean visit(double a1,double a2,int a3);
	boolean visit(double a1,double a2,long a3);
	boolean visit(double a1,double a2,float a3);
	boolean visit(double a1,double a2,double a3);
	boolean visit(double a1,double a2,Object a3);
	boolean visit(double a1,Object a2,int a3);
	boolean visit(double a1,Object a2,long a3);
	boolean visit(double a1,Object a2,float a3);
	boolean visit(double a1,Object a2,double a3);
	boolean visit(double a1,Object a2,Object a3);
	boolean visit(Object a1,int a2,int a3);
	boolean visit(Object a1,int a2,long a3);
	boolean visit(Object a1,int a2,float a3);
	boolean visit(Object a1,int a2,double a3);
	boolean visit(Object a1,int a2,Object a3);
	boolean visit(Object a1,long a2,int a3);
	boolean visit(Object a1,long a2,long a3);
	boolean visit(Object a1,long a2,float a3);
	boolean visit(Object a1,long a2,double a3);
	boolean visit(Object a1,long a2,Object a3);
	boolean visit(Object a1,float a2,int a3);
	boolean visit(Object a1,float a2,long a3);
	boolean visit(Object a1,float a2,float a3);
	boolean visit(Object a1,float a2,double a3);
	boolean visit(Object a1,float a2,Object a3);
	boolean visit(Object a1,double a2,int a3);
	boolean visit(Object a1,double a2,long a3);
	boolean visit(Object a1,double a2,float a3);
	boolean visit(Object a1,double a2,double a3);
	boolean visit(Object a1,double a2,Object a3);
	boolean visit(Object a1,Object a2,int a3);
	boolean visit(Object a1,Object a2,long a3);
	boolean visit(Object a1,Object a2,float a3);
	boolean visit(Object a1,Object a2,double a3);
	boolean visit(Object a1,Object a2,Object a3);
}
